### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module not supported.

### ISSUE THREAD

**Issue by iamarthurk** [broofa/mime#296] opened 2023-12-05 00:14 UTC
I get an error when trying to require the module.

`import mime from 'mime';`

<img width="1391" alt="Screenshot 2023-12-05 at 3 22 40 AM" src="https://github.com/broofa/mime/assets/95454079/028503a7-f331-404c-8b3e-b90812b3e2e0">

"mime": "^4.0.0-beta.1",
"typescript": "^5.2.2",
"ts-node": "^10.9.1",

lite is also not there 

<img width="1004" alt="Screenshot 2023-12-05 at 3 21 54 AM" src="https://github.com/broofa/mime/assets/95454079/e47101f6-c708-45ee-a3aa-67b01814087b">

**Comment by broofa** [comment] 2023-12-05 13:18
* Please update to `mime@latest` (not that I expect this to make a difference.)
* Please copy/paste the output of `npm ls mime` here
* Please copy/paste the output of `npx envinfo --system --browsers --npmPackages --binaries` here

If nothing obvious comes of that, I'll need you to put together a small, self-contained, reproduceable use case that will allow me to recreate the error.

Thanks!

**Comment by broofa** [comment] 2023-12-05 16:04
Actually, that first error pretty clearly states that `media.ts` is using `require()`, which won't work with `mime@4`.  As noted in this project's README, `mime` is now ESM-only, so you'll need to `import` or `import()` it.  If you really need to `require()`, 'probably best to stick with `mime@3` for the time being.

As for the "Cannot find module 'mime/lite' ...", make sure you have `"type": "module"` in your package.json file.   I was able to reproduce your problem with a small test project:

![CleanShot 2023-12-05 at 08 00 53@2x](https://github.com/broofa/mime/assets/164050/1aed15d1-31d5-4204-b6db-b19316a01635)


Adding `"type": "module"` to the package.json, and setting `"module": "NodeNext"` in tsconfig.json fixed the problem:

![CleanShot 2023-12-05 at 08 01 42@2x](https://github.com/broofa/mime/assets/164050/9e5732be-47d2-4fe1-9d40-999749022548)

("moduleResolution" may or may not also be useful, per https://github.com/microsoft/TypeScript/issues/49670#issuecomment-1169336444.)

**Comment by GCRev** [comment] 2023-12-11 08:02
I just ran into this and spent about half an hour attempting to adapt my (not very large) project to work with ESM, which is a mistake when using Typescript, because it defaults to CommonJS and doesn't provide a lot of help regarding ESM. Changing the `tsconfig` over does a whole bunch of unexpected things to the project as well (such as confusing relative imports). This is probably mostly in Typescript's court to develop the tools that can handle this properly, but the onus to adapt a project directly is still largely on the devs.

`"type": "module"` in `package.json` is still -- in my opinion -- a mistake with Node 21 and Typescript. I suppose I can use an older version of this package that'll work with CommonJS's compiled `require`'s.

I'd be cautious about proceeding with ESM-only. Node + Typescript still doesn't seem like it's there yet, unfortunately.

**Comment by broofa** [comment] 2023-12-11 15:03
TS + ESM works. There's plenty of emperical evidence of that (including this project's codebase.)

Much as I enjoy opining on the merits and flaws of various toolchains, this isn't really the place for that so let's not go there.

Closing this issue, as there's no actionable issues at this time.  'Happy to reopen if someone wants to put up an [MRE](https://stackoverflow.com/help/minimal-reproducible-example) that justifies it.

**Closed by broofa** 2023-12-11 15:03 UTC

**Comment by iamarthurk** [comment] 2023-12-16 13:11
Hello, sorry for the late reply, the situation described by @GCRev is exactly the case, changing the type to module in package.json and module in tsconfig caused tons of issues, with relative imports, etc.

I will prepare an MRE in the upcoming days if I get some free time, it is up to you whether you will take a look at this or not.

Thanks.

**Comment by broofa** [comment] 2023-12-16 15:41
Thanks, @iamarthurk, that'd be great.  'Happy to take a look.
